name: Build and Deploy to AKS

on:
  push:
    branches: [ master ]  # Change to 'main' if your branch is named 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: v1.0.0
      IMAGE_NAME: arithmetic-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build project (skip tests)
      run: mvn --batch-mode -DskipTests package

    - name: Run unit tests
      run: mvn test

    - name: Log in to Azure Container Registry
      run: |
        echo "${{ secrets.AZURE_PASSWORD }}" | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.AZURE_USERNAME }} --password-stdin

    - name: Build and push image to ACR
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$IMAGE_NAME:$VERSION .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$IMAGE_NAME:$VERSION

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set kubeconfig from secret
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Make deploy.sh executable
      run: chmod +x ./deploy.sh

    - name: Deploy to AKS
      run: ./deploy.sh
